version: '3'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - 8080:8080
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./server/public:/usr/share/nginx/html/public
    depends_on:
      - php
  php:
    build: ./docker/php
    volumes:
      - ./server:/var/www/html
